##### Wykonaną pracę domową wrzucamy na swojego GitHuba, repo kp, nazwa pliku s01_pd02.ipynb. Deadline: 25.11.2017

## Listy

In [7]:
#pracujemy na tej liście
l = [1,[2,[3,4],5],6,7,[8],9,10,[11,12,[13,14],15],16,[17,18,[[19,20,21,22,23],24],[25,26],27],28]

In [8]:
#Dostań się do podanej lub podanych wartości przez indeksowanie
# 0
# 5
# 4
# 10
# [[2, [3, 4], 5], 6, 7, [8]]
# [11, [13, 14]]
# 24
# 8
# [23, 22, 21, 20, 19]

In [9]:
l[1][2]

5

In [10]:
l[1][1][1]

4

In [11]:
l[6]

10

In [12]:
l[1:5]

[[2, [3, 4], 5], 6, 7, [8]]

In [22]:
l[7][0::2]

[11, [13, 14]]

In [26]:
l[9][2][1]

24

In [28]:
l[4][0]

8

In [34]:
l[9][2][0][::-1]

[23, 22, 21, 20, 19]

## Funkcje

In [76]:
#znajdź funkcję, która służy do łączenia ścieżek;
#połącz folder, w którym obecnie pracujesz (wykorzystaj do tego odpowiednią funkcję)
#z folderem o nazwie 'Tygrysek_Kazimierz'. Wynik tego zapisz w zmiennej kazio. Wydrukuj zmienną kazio.

In [44]:
import os
jestem_tu = os.getcwd()
os.getcwd()

'C:\\Users\\amydi\\Desktop\\Python\\KOŁO\\py-master'

In [73]:
kazio = os.path.join(jestem_tu, 'Tygrysek_Kazimierz')
print(kazio)

C:\Users\amydi\Desktop\Python\KOŁO\py-master\Tygrysek_Kazimierz


In [78]:
#korzystając z pewnej nieodgadnionej funkcji,
#podziel zmienną kazio tak, aby każdy kolejny folder był oddzielnym elementem na liście. Zapisz to jako kazio2.
#wybierz z tak stworzonej listy nazwę użytkownika.

kazio2 = os.path.normpath(kazio).split(os.path.sep)

In [79]:
kazio2

['C:',
 'Users',
 'amydi',
 'Desktop',
 'Python',
 'KOŁO',
 'py-master',
 'Tygrysek_Kazimierz']

In [85]:
kazio2[2]

'amydi'

## Numpy

In [20]:
#zaimportuj odpowiedni pakiet do pracy z wektorami i macierzami
import numpy as np

In [2]:
#wektor ar
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [65]:
#doklej do wektora ar wartości [4,5,9,10,23,-14,55,13]
ar2 = np.array([4,5,9,10,23,-14,55,13])
ar3 = np.append(ar, ar2)
ar3

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [41]:
#znajdz index dla wartości 9 - użyj odpowiedniej funkcji
index = np.where(ar3 == 9)[0][0]
index

14

In [40]:
#znajdź indeksy dla wartości mniejszych od zera - użyj odpowiedniej funkcji
np.where(ar3 < 0)[0][:]

array([ 2,  5,  8, 17], dtype=int64)

In [58]:
#wyświetl wartości mniejsze od zera
mniejsze_od_zera = [ 2,  5,  8, 17]
ar3[mniejsze_od_zera]

array([ -3, -10, -98, -14])

In [59]:
#policz średnią, zaokrąglij do jednego miejsca po przecinku
np.mean(ar3)

12.1

In [64]:
#stwórz zmienną ar_abs, wektor wartości bezwględnych z wektora ar
ar_abs = np.abs(ar)
ar_abs

array([ 1,  2,  3,  6,  7, 10, 88, 43, 98, 17, 39, 45])

In [107]:
#stwórz zmienną ar_p, wektor pierwiastków trzeciego stopnia z wektora ar
ar_p = np.cbrt(ar)
ar_p

array([ 1.        ,  1.25992105, -1.44224957,  1.81712059,  1.91293118,
       -2.15443469,  4.44796018,  3.50339806, -4.61043629,  2.57128159,
        3.39121144,  3.5568933 ])

In [113]:
#zaokrąglij wektor ar_p do dwóch miejsc po przecinku
ar_p_z = np.round(ar_p, 2)
ar_p_z

array([ 1.  ,  1.26, -1.44,  1.82,  1.91, -2.15,  4.45,  3.5 , -4.61,
        2.57,  3.39,  3.56])

In [119]:
#zsumuj zaokrąglony wektor ar_p i podnieś go do kwadratu, 
#zmienną nazwij ar_sq, zmień typ tej zmiennej na liczbę całkowitą

np.sum(ar_p_z)

15.26

In [121]:
ar_sq = np.power((np.sum(ar_p_z)), 2)
ar_sq

232.86759999999998

In [131]:
ar_sq.astype(np.int64)

232